### ISSUE TITLE
1.14 Support

### ISSUE THREAD

**Issue by JammMusic** [PaperMC/Travertine#101]
It says 1.14.x support on the client server list, but it still shows a red x on the ping, and doesn't let you join with 1.14.

Thanks for keeping this software up to date :)

**Comment by electronicboy** [comment]
Appears to be working fine here, make sure that you don't have any plugins installed that might be causing issues due to the new protocol version
![image](https://user-images.githubusercontent.com/1228900/56606558-64dfd500-65fe-11e9-9c24-31bdf692e782.png)
