### ISSUE TITLE
Add 1.14.1 support

### ISSUE THREAD

**Issue by Xayanix** [PaperMC/Travertine#103]
Add 1.14.1 support

**Comment by Aurelien30000** [comment]
**I quote :** 
Electroniccat
"No If somebody wants to submit a PR I'll happily consider it, but I have no interest in digging down on a patch that will be removed in a day or so"

xD

**Comment by zachbr** [comment]
Shouldn’t this be on the Waterfall repo?

**Comment by Xayanix** [comment]
> Shouldn’t this be on the Waterfall repo?

Probably, i didn't check it. Thought they have to merge upstream only.

**Comment by Artuto** [comment]
FYI upstream already supports 1.14.1 https://github.com/SpigotMC/BungeeCord/commit/3ec223ec94d02b1578be251cedc600689e43035f

**Comment by zachbr** [comment]
Soon™
