### ISSUE TITLE
Already connected

### ISSUE THREAD

**Issue by Acenox** [PaperMC/Travertine#106]
Hello,

I encounter a problem weird for some time on Travertine, from time to time my players lose the connection randomly on my different servers, I have traced the logs of spigot and proxy.

We can see that the player "Xyphool" timeout at 20:15:16 but that the proxy does not interpret it, he does not recognize that the player has disconnected, the problem is that suddenly the player remains on the server Faction and has the error "You are Already connected".

Would you help me?

Spigot log: https://pastebin.com/qsyUPXCW
Travertine: https://pastebin.com/MRVNcbyG

The only error we can have is this: [20:15:31] [Netty Worker IO Thread #14/WARN]: Event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[/81.49.163.223:50611|Xyphool] <-> InitialHandler) took 377ms to process!

Best regards,

**Comment by electronicboy** [comment]
it's saying they're still connected to the server or the proxy? Do you have any plugins?
The error you've also quoted means that an event took too long to process, generally down to plugins on the proxy

**Comment by Acenox** [comment]
Hello,
Thank you for your answer, they still seem connected to the proxy because at the server, they are no longer connected. I actually have some plugins, so it's very likely that it comes from there.

- blockservercmd
- Bot-Sentry
- BungeeAdminTools
- BungeeAntiPlugins
- BungeeDisplays
- Bungeeservermanager
- Bungeelist
- Executeeverywhere
- LiteAnnouncer
- MySkin
- Permissioncord
- PremiumConnector
- RandomHub
- SkUngee
- Yamler-Bungeecord

Namely, that I have not updated my plugins since 2018 at least, and that I encounter this problem for about 2 months, so it is quite possible that it is an incompatibility with a plugin following the addition of support for the 1.14 (I use ViaVersion & ViaRewind on my servers)

Best regards,

**Comment by electronicboy** [comment]
You should rule out plugins causing these issues before opening tickets, that we we can either pull it down to plugin behaving badly or some behavioral change we need to address, I would suggest updating your plugins and maybe trying to pull them one by one if that doesn't resolve it
