### ISSUE TITLE
BungeeAdminTools compatibility issues

### ISSUE THREAD

**Issue by samtaber** [PaperMC/Travertine#113]
Travertine's build number is less that 878, which BAT requires to run. Is there any way I could modify the build number? I tried modifying the BAT code (since its open source) but its throwing errors since the code doesn't work for some reason.

**Comment by astei** [comment]
The version check is broken because it assumes nobody would ever do something crazy like modify BungeeCord.

For the record, build 878 of BungeeCord is over 5 years old and few people are using such an ancient version of BungeeCord these days.
