### ISSUE TITLE
Bungee.Protocol.EntityEffect - Sevtech disconnect

### ISSUE THREAD

**Issue by Adam3055** [PaperMC/Travertine#115]
Hi there, we recently setup a Sevtech server and when you go to fly around on the server you will randomly get disconnected and kicked, nothing comes up in the Sevtech console other than user disconnected, but in travertine console it seems to throw an error? 

![Untitled](https://user-images.githubusercontent.com/46658894/66503213-b867b180-eabe-11e9-96a2-f24ebf7a4c0d.png)

"|Keaton_wizard] <-> DownstreamBridge <-> [Sevtech] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.EntityEffect 79 Protocol GAME Direction TO_CLIENT"

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Travertine/issues/102
