### ISSUE TITLE
Titles don't show up on 1.8

### ISSUE THREAD

**Issue by camdenorrb** [PaperMC/Travertine#116]
![image](https://user-images.githubusercontent.com/5360339/67534888-d1af5700-f695-11e9-9262-a7acb003ec97.png)

This code works perfectly fine, it just only shows up for players using 1.12+ clients

Only tested [1.8, 1.12, 1.14.4]

**Comment by camdenorrb** [comment]
Just realized that travertine only supports 1.7, closing lol...

**Comment by mikroskeem** [comment]
Wrong, Travertine supports 1.7.x - 1.14.x

**Comment by electronicboy** [comment]
Would more be https://github.com/PaperMC/Waterfall, would also be interesting to know if this occurs on bungee too

**Comment by camdenorrb** [comment]
It appears setting fadeIn, stay and fadeOut fixed this. It might also be good to note that it seemed to break randomly.
