### ISSUE TITLE
player kick, nbt related error

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Travertine#119]
https://pastebin.com/raw/VcsFBry7

**Comment by electronicboy** [comment]
Not really an issue on our side from what I can see, bad NBT tag?

**Comment by PhanaticD** [comment]
that stacktrace in travertine log is only info i can find, i went to the location the player logged in there was nothing there

**Comment by electronicboy** [comment]
There have been no further updates on this, and I'm inclined to believe that this was an upstream bungee issue
