### ISSUE TITLE
Trvertine Exception Issue

### ISSUE THREAD

**Issue by DebuffPvP** [PaperMC/Travertine#122]
Hi sometimes i get this error on travertine the newest version and sometimes it doesn't happen

https://pastebin.com/bZbayZ1Y

**Comment by lhridder** [comment]
I think this has nothing to do with Travertine and your plugin is broken. Does it work on Waterfall or just normal BungeeCord?

**Comment by Chew** [comment]
Around this time I believe the session server IP changed. You can also customize it now if needed as of latest build. If this is still an issue, feel free to let us know. Have a good day!
