### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException

### ISSUE THREAD

**Issue by luanmenglei** [PaperMC/Travertine#123]
I'm using centos 7
jdk8
And my Travertine worked my perfectly on the win server 2019
But when I change to the Linux.
Every time a player changes the server, it has a chance there will be a io.netty.channel.unix.Errors$NativeIoException

**Comment by electronicboy** [comment]
`io.netty.channel.unix.Errors$NativeIoException` occurs when a network I/O issue occurs outside of our control
