### ISSUE TITLE
Minecraft Message Protocol Text Json Format Byte Code

### ISSUE THREAD

**Issue by ByteCompiler** [PaperMC/Travertine#124]
I want write bukkit multi version from 0, i want analyze int byte to int byte;to create a server 100% autonomous and free of bugs that occur in community edition;

I would like help to establish the tools for the message protocols;what are those "??" in the message data? what tools can i use to read?

is it possible to communicate with the minecraft protocol through json code texts like i saw on some nodejs and wikis servers or do i have to test all int bytes ?

![image](https://user-images.githubusercontent.com/62629405/79924906-76291080-840f-11ea-8070-25a7fffe84be.png)

**Comment by electronicboy** [comment]
This is an issue tracker, not a call for assistance with unrelated... whatever the heck you're doing...
There is well-established documentation of the protocol on wiki.vg

**Comment by ByteCompiler** [comment]
when i unzip using zlib i will get a json text protocol format?

**Comment by electronicboy** [comment]
No. read the protocol docs.
