### ISSUE TITLE
Travertine Add 1.5.2 1.4.7 Version like ProtocolSupport

### ISSUE THREAD

**Issue by ByteCompiler** [PaperMC/Travertine#125]
I would like to edit the travertine myself; but i don't know how to start and the real github code looks incomplete from both the bungeecord, waterfall and travertine;

Could you provide me with the code you work with?

My JD GUi decompiles everything wrong and I have to fix it manually; does it have a decompiler that does not have to work manually to correct the decompilation errors?

To downgrade to 1.5 to test for errors I just need to copy the same structure as 1.7?

Minecraft works with json? could i test the errors by seeing the json structure changes or is there a connection testing tool that analyzes the network data byte by byte?

**Comment by electronicboy** [comment]
compile as per the readme, you'll then have the source
