### ISSUE TITLE
mc message protocol

### ISSUE THREAD

**Issue by ByteCompiler** [PaperMC/Travertine#126]
I read wiki docs protocol, I can think of infinite meanings, I don't know which of the meanings is real because I haven't yet lived the reality in which I transformed it into something different than what they are;

**Comment by ByteCompiler** [comment]
Before creating a public repository, learn basic quantum physics;

**Comment by ByteCompiler** [comment]
You don't even know the learning algorithm in your mind, you say things with such conviction that you can't help anyone;

**Comment by ByteCompiler** [comment]
If you want to create one comunnity project you must learn how to converse with people using their language, unlike you will only be a limited light spot;

**Comment by zachbr** [comment]
We can't offer you the help you need.
