### ISSUE TITLE
Only 2 players can be at one server at once

### ISSUE THREAD

**Issue by EgZiG** [PaperMC/Travertine#127]
Only 2 players can be at one server at once, when 3rd player want to join, they get this error: https://prnt.sc/sixpu1

**Comment by EgZiG** [comment]
PLSSSSSSS HELP

**Comment by electronicboy** [comment]
That's a generic "the connection failed", you'd need to check the proxy logs for more information, this often implies that there is something screwing with the network or you're just connecting them to a dead server.

**Comment by EgZiG** [comment]
ok so how to fix that, server is not dead and there is nothing in proxy logs

**Comment by EgZiG** [comment]
it cant be dead server causew 2 other player can connect , when i send 1 player to other server , the i can join
