### ISSUE TITLE
How to pull from Upstream?

### ISSUE THREAD

**Issue by LinsaFTW** [PaperMC/Travertine#140]
Hi, i have been trying to figure this out for months without any clues. I am new at this git stuff and i don't really understand how it works. I am trying to pull from Upstream with some patches done to the Travertine source and then pulling to get the 1.16.2 update but it isn't pulling stuff from Upstream.

/travertine p output
https://hastebin.com/imenociwok.sql

Thanks.

**Comment by PurpleStormCloud** [comment]
Did you update the submodule Waterfall (assuming this is a modified travertine) with `./travertine up` and then rebuild your changes? Assuming you just modified travertine, I would suggest you clone the current Travertine repo, put your extra patches in the patches folder, rebuild the patches and go from there

**Comment by LinsaFTW** [comment]
> Did you update the submodule Waterfall (assuming this is a modified travertine) with `./travertine up` and then rebuild your changes? Assuming you just modified travertine, I would suggest you clone the current Travertine repo, put your extra patches in the patches folder, rebuild the patches and go from there

Hi, please explain carefully what i have to do, because i just lost all my changes by doing ./travertine rb :/

**Comment by electronicboy** [comment]
Up, patch, fix any issues, rebuild

**Comment by LinsaFTW** [comment]
> Up, patch, fix any issues, rebuild

Thats exactly why i asked for more detailed info. I dont understand that terms. I already readed the CONTRIBUTING.md on how to pull but it gives me the error i described in the first message.

**Comment by electronicboy** [comment]
Remove the spaces in the path, that would be my guess

**Comment by LinsaFTW** [comment]
Hi, that fixed some issues with /travertine rb but it is still not compatible with 1.16.2 after doing /travertine b and getting the jar from /Travertine-Proxy/bootstrap. Do i have to do something else?

https://hastebin.com/okigodaniw.sql

**Comment by LinsaFTW** [comment]
I just noticed it is trying to take stuff from a old folder that doesn't exist anymore. What could be causing this?

It is taking stuff from the users/downloads/... folder instead of /files/workspaces/...

**Comment by LinsaFTW** [comment]
Another Update:

I re-cloned Travertine to a new folder without touching anything then i moved Travertine-Proxy files from FlameCord into Travertine-Proxy folder of the new cloned Travertine.

For some reason every pom fails to merge because of conflicts: https://hastebin.com/kokukaqusi.sql

What can i do from here? I am trying to understand this as much as possible.

**Comment by LinsaFTW** [comment]
Okay, after 12 hours of try/fail i now understand the Patch system. But now my problem is that Travertine/Waterfall patch system is broken because it generates the folder path when built so now that i am using another path (moved from downloads to minecraft-workspace) it tries to use the unexistant downloads path.

What can i do from here? It seems now like an issue from Travertine/Waterfall that i can't solve. I don't want to lose the source, i already recoded FlameCord 3 times because of not understanding the patch system.

**Comment by PurpleStormCloud** [comment]
@LinsaFTW if you still need help DM me on discord `@stormfront#5479`

**Comment by LinsaFTW** [comment]
Okay. Thanks for all the help on Discord, Purple. I was able to fix this with the following steps to pull from upstream:

1. I made my patch as CONTRIBUTING.md specifies.
2. When i tried to `travertine p` it gave merge errors with my patch, this is what i did to fix the issues:
 2.1. Open all files listed on the "merge error" message with your favorite text editor.
 2.2. You will see that each file has a "<<< head" text added on the files, this is to identify between the incoming change and the current change.
 2.3. To fix merge issues just modify the files to make them how they should be at the end of the merge; You have to remove all the "<<<"s and just let one of the changes (incoming/current) on your file.
 2.4. After this, on the `Travertine-Proxy` directory, you have to write `git add *` and then `git am --continue`.
 2.5. Then you have to do `travertine rb` otherwise it will show that there still are conflicts.

After this you can build your project normally with `travertine b`.
