### ISSUE TITLE
Tabbing completion doesn't always work on java 15

### ISSUE THREAD

**Issue by assasin541** [PaperMC/Travertine#144]
Tabbing completion doesn't always work on java 15

**Comment by electronicboy** [comment]
any errors, or any form of information beyond "doesn't work"?
The version of java is likely 100% irrelevant here, and more likely down to plugins, etc

**Comment by assasin541** [comment]
@electronicboy sometimes you just can't tab any nickname. It started to happen after updating java to 15.

**Comment by electronicboy** [comment]
There is no information here for me to go off, completion of nick names is done by the client, not the server, common issues here are oddball plugins messing with the tab list, etc

**Comment by assasin541** [comment]
@electronicboy even if I use TabCompleteEvent on bungee and add players to it? Thanks for closing

**Comment by electronicboy** [comment]
TabCompleteEvent is not fired for nickname completions, only for commands, which are handled on the server

**Comment by assasin541** [comment]
@electronicboy yes! I call this event in commands to get players, you get it?

**Comment by electronicboy** [comment]
Well, provide basic info, you're giving me nothing to go off here, it's not the expectation that we're going to flood peoples email accounts trying to get basic info.

Can the client see the command? Do they have perms? Where is the plugin for this running? Can they see any commands? etc, etc

**Comment by assasin541** [comment]
@electronicboy what email?

Yes. Yes. On the server in plugins. Yes? 1.8/1.16 client, server Travertine.
