### ISSUE TITLE
1.7 crash

### ISSUE THREAD

**Issue by assasin541** [PaperMC/Travertine#146]
When you join the server with 1.7 you get crashed

**Comment by assasin541** [comment]
--- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 12.11.20 02:23
Description: Ticking screen

java.lang.IndexOutOfBoundsException
    at java.nio.Buffer.checkIndex(Buffer.java:540)
    at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
    at bls.a(SourceFile:270)
    at bls.a(SourceFile:220)
    at azd.a(SourceFile:1675)
    at azd.a(SourceFile:1633)
    at biv.a(SourceFile:113)
    at gu.a(SourceFile:70)
    at gu.a(SourceFile:13)
    at ef.a(SourceFile:164)
    at bbe.c(SourceFile:76)
    at azd.o(SourceFile:131
    at azd.ad(SourceFile:753)
    at azd.e(SourceFile:704)
    at net.minecraft.client.main.Main.main(SourceFile:103)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.nio.Buffer.checkIndex(Buffer.java:540)
    at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
    at bls.a(SourceFile:270)
    at bls.a(SourceFile:220)
    at azd.a(SourceFile:1675)
    at azd.a(SourceFile:1633)
    at biv.a(SourceFile:113)
    at gu.a(SourceFile:70)
    at gu.a(SourceFile:13)
    at ef.a(SourceFile:164)
    at bbe.c(SourceFile:76)

-- Affected screen --
Details:
    Screen name: bbe

-- Affected level --
Details:
    Level name: MpServer
    All players: 0 total; []
    Chunk stats: MultiplayerChunkCache: 0, 0
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,, Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
    Forced entities: 0 total; []
    Retry entities: 0 total; []
    Server brand: ~~ERROR~~ NullPointerException: null
    Server type: Non-integrated multiplayer server
Stacktrace:
    at biz.a(SourceFile:284)
    at azd.b(SourceFile:1951)
    at azd.e(SourceFile:713)
    at net.minecraft.client.main.Main.main(SourceFile:103)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 107465128 bytes (102 MB) / 201326592 bytes (192 MB) up to 2147483648 bytes (2048 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
    AABB Pool Size: 18497 (1035832 bytes; 0 MB) allocated, 18497 (1035832 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: 1.7.2
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
    Is Modded: Probably not. Jar signature remains and client brand is untouched.
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)

**Comment by Chew** [comment]
This seems like more of an issue with the server you're joining, not necessarily Travertine itself. What are you joining?

**Comment by assasin541** [comment]
@Chew cpvp.pl

**Comment by Shevchik** [comment]
View distance >_<

**Comment by Xernium** [comment]
What @Shevchik is trying to say is what I suspected but didn’t reply for because I didn’t think it’d be caused by this. Go into the video settings and change your render distance to anything on 1.7
It can literally be anything as long as you set it while being on 1.7.
Playing on a newer version, you set the render distance to something 1.7 can’t deal with; this is the fix to it.

**Comment by assasin541** [comment]
@Shevchik @Xernium @electronicboy is there a way to avoid this server-side?

**Comment by Xernium** [comment]
@assasin541 if there were then a patch for that would already exist. No there is not.
