### ISSUE TITLE
 Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException

### ISSUE THREAD

**Issue by xingboyu1** [PaperMC/Travertine#149]
![image](https://user-images.githubusercontent.com/61927455/105689409-b0db4e80-5f35-11eb-8e46-4857fed05712.png)
![image](https://user-images.githubusercontent.com/61927455/105689488-c9e3ff80-5f35-11eb-94b9-1f97ec85eded.png)
![image](https://user-images.githubusercontent.com/61927455/105689515-cf414a00-5f35-11eb-8167-f4214066050f.png)
What should i do？

**Comment by electronicboy** [comment]
The issue tracker is for reporting issues, not seeking support, you're also using a stupendously old version of travertine.
As for the error, can't say, that exception covers many general "we failed to connect scenarios", generally network configuration related
