### ISSUE TITLE
Can't compile if one of the parent folders have spaces

### ISSUE THREAD

**Issue by linsaftw** [PaperMC/Travertine#154]
If one of the parent folders has a space character Travertine will not compile.

**Comment by LinsaFTW** [comment]
> You had the same problem in #140 and again the solution was to remove the spaces from your path.

Id like having it fixed so i don't run into the same problem everytime i have a folder with spaces.

**Comment by electronicboy** [comment]
You've not even provided the error, build issues due to mangled environments are not all that high of a priority for me to run around replicating

**Comment by LinsaFTW** [comment]
Aight, this is the error.
![image](https://user-images.githubusercontent.com/25271111/110489286-07f44780-80ce-11eb-8497-4d8b803989d9.png)
