### ISSUE TITLE
Players being kicked from modded server

### ISSUE THREAD

**Issue by Eufranio** [PaperMC/Travertine#47]
The players are kicked every time they connect with my modded 1.7.10 server.

Stacktrace:
```
[WARNING] [/201.87.196.159:52399|V_Losker_V] <-> DownstreamBridge <-> [BlackCraft] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.EntityEffect 29 Protocol GAME Direction net.md_5.bungee.protocol.Protocol$DirectionData@213ada
01:34:37 [INFO] [/201.87.196.159:52399|V_Losker_V] <-> DownstreamBridge <-> [BlackCraft] has disconnected
```

**Comment by Time6628** [comment]
I am also getting the same error with the modpacks [Augment Triad](https://www.atlauncher.com/pack/AugmentedTriad) and [Unabridged](https://www.atlauncher.com/pack/Unabridged).

**Comment by Time6628** [comment]
Here's the client side crash, https://pastebin.com/D69dDf7k.
