### ISSUE TITLE
1.7.10 Forge Server and Client, Connection gets Terminated right after successful join

### ISSUE THREAD

**Issue by psych0d0g** [PaperMC/Travertine#78]
So i setup a Proxy server handling connections from clients to a paper server (using protocolsupport plugin) fine, they then get redirected to my mod server fine aswell.
As soon as the client connected and the World is displayed on the client, the connection gets terminated and my client gives me a few stacktraces [1]. Travertine itself just gives me a single error on the console [2].
This happens aswell if i take the paper server out of the equation and just use Client -> Travertine -> Forge Server.
Client -> Forge server works without any issues.
After looking at the Stacktraces of my Client and some researching i think my problem is related by a custom packet generated by the "Code Chicken Lib" [3]

[1] https://paste.crystalnet.org/?da1008dd38712027#kVWjS0FEC/cGUMl6OjT3/0TzA1i0V5xeHe9Nw2ryh+8=
[2] https://paste.crystalnet.org/?c444e5f08707cd73#hxFAB6Kb8NyBWpp4aKVVa1U2Gw/blja4uNGhTP4M/Gk=
[3] https://github.com/TheCBProject/CodeChickenLib/blob/master/src/main/java/codechicken/lib/packet/PacketCustom.java

**Comment by psych0d0g** [comment]
Additional Info:
Similar Modded 1.12 sponge server works fine…
Ill compare the mods loaded on each later on, just know that codechickenlib 1.8+ is in use there (not sure how extensively it was rewritten.)

**Comment by alicheek** [comment]
I can plus one this issue that @psych0d0g  has had with the latest travertine build

**Comment by Keaton1188** [comment]
Can confirm, this is still an issue.

**Comment by electronicboy** [comment]
Pastes have expired, would need to see new ones

**Comment by Keaton1188** [comment]
Client log when Fatal Error happens - https://pastebin.com/dF67VVGa

Travertine just shows disconnected, this error does not happen on an older version of travertine that we use to prevent this from happening, as to what build that is I'm not sure.

**Comment by electronicboy** [comment]
By any chance, is the older version directly connecting to that modded server?
Does connecting to the modded server directly through the proxy (default server, forced hosts) does it work?

**Comment by alicheek** [comment]
Hey @electronicboy this is when we used a forced host to connect so from our IP: inf.brierie.net which forced to our infinity server which is a 1.7.10 server

**Comment by alicheek** [comment]
@electronicboy  The older version was connecting our servers from 1.7.10 to 1.12.2 the new version does 1.10.2 - 1.12.2 only it seems due to the issue above

**Comment by Keaton1188** [comment]
The old build that we are using that works is Build-40 if that helps.

**Comment by alicheek** [comment]
@electronicboy Think this is something that can be fixed as the new build of course does fix other issues with our 1.12.2 servers

**Comment by electronicboy** [comment]
This is something I'd need to look into, ForgeMultipart is throwing an exception, yet that exception is getting squashed out because of another exception thrown due to their bad exception handling, meaning that we can't see the original exception which caused the issue

@Keaton1188 There are 33 builds between now and 40, if you can identify the exact build/commit which broke it, that would be of much more use

**Comment by Keaton1188** [comment]
I'll do some testing and will report back when we find out anything
