### ISSUE TITLE
Error decoding packet class Handshake with contents

### ISSUE THREAD

**Issue by minecraft7net** [PaperMC/Travertine#84]
i have something with multiple times replaced - 36199 the same error generated by one IP

[21:19:00] [Netty Worker IO Thread #1/ERROR]: [/195.62.13.216:11124] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents:

https://pastebin.com/w8hjcUp9

https://pastebin.com/QcumCAK7

is it plugin or something else?

**Comment by electronicboy** [comment]
That IP address is sending invalid traffic to the server
