### ISSUE TITLE
Randomly getting kicked on 1.13 paperspigot

### ISSUE THREAD

**Issue by runescapejon** [PaperMC/Travertine#87]
On paperspigot on 1.13.2 for some odd reason i am getting kicked https://pastebin.com/raw/9MPPtrHc

it seem it's related to a close issue here https://github.com/PaperMC/Waterfall/issues/178

**Comment by electronicboy** [comment]
Your server sent an empty packet, this is not an issue with the proxy

**Comment by runescapejon** [comment]
So there ain't a way to fix this from happening?

**Comment by electronicboy** [comment]
You need to work out what is causing these empty packets to be sent on your server

**Comment by runescapejon** [comment]
ah okay thanks
