### ISSUE TITLE
Travertine Kick

### ISSUE THREAD

**Issue by AntoLuMeju99** [PaperMC/Travertine#98]
Hi, when a server crash, users dont be sended to hub, but they will be kicked out of the server. How i can solve?

**Comment by electronicboy** [comment]
There are plugins such as MoveMeNow and HubKick which attempt to achieve this, I believe that bungee itself doesn't have this built in because it's hard to determine crash/vs an actual kick

**Comment by AntoLuMeju99** [comment]
MoveMeNow dont work

**Comment by SiebeDW** [comment]
I used movemenow a month ago, it worked for me. U probalby configured it bad.

**Comment by AntoLuMeju99** [comment]
It said that i'm already connected to this server....
